### ISSUE TITLE
Why not fill the gaps on KernelNewbies?

### ISSUE THREAD

**Issue by niamster** [0xAX/linux-insides#108]
There's already a [wiki](http://kernelnewbies.org/) where people document different parts of the kernel. It would be better to put all the stuff there.

**Comment by 0xAX** [comment]
@nathansoz Github is more convenient for me, if somebody will wants to sync it with kernelnewbies, it can do it

**Comment by TheCodeArtist** [comment]
I agree that maintaining this on github looks easier.

However, without an explicit license its a risk for anyone to simply copy-paste stuff (though its out in the open) from here to elsewhere. Let bump-up https://github.com/0xAX/linux-insides/issues/57
