### ISSUE TITLE
Capitalisation of sub-directories and other writing guidelines

### ISSUE THREAD

**Issue by TheCodeArtist** [0xAX/linux-insides#115]
Is there a special reason for not capitalising all other chapter directories except "interrupts" and "mm" ?

1. If no reason, then can i submit a pull-request removing the capitalisation of few directories?
2. Also better to have a writing-guideline.md describing common conventions to follow (and avoid) across all files.

**Comment by 0xAX** [comment]
> Is there a special reason for not capitalising all other chapter directories except "interrupts" and "mm" ?

No there are no special reasons, it even was `MM` previously. But I changed it on `mm` as you can see it now. There is only one reason why I did it and it is not important. I just think that `mm` looks better, that's all. But in other way, all directories start from the capital letter and `MM` must
 be too...

> Also better to have a writing-guideline.md describing common conventions to follow (and avoid) across all files.

Yes, It is great idea. For now we just have how to submit PR and it will be very good to have guide how to fix/write and format the text. Would you like to start to write it or it was just suggestion? If you are agree, I will no close this issues and we can discuss it here.

Thank you.

**Comment by TheCodeArtist** [comment]
I think all small would look neat as long as features git-book/links do not break.
(kind of like how everything in my code usually begins with small letters)

Let me take a first stab at a "writing-guidelines.md".
Based on what i see in the repo i will come-up with a few initial guidelines.

Lets close this issue once we arrive at a final draft that can be merged.
For now, can you assign this issue to me (on github) as a reminder?

**Comment by 0xAX** [comment]
> I think all small would look neat as long as features git-book/links do not break.
(kind of like how everything in my code usually begins with small letters)

Yes, forgot about this. There are many links to the `mm` in the book.

>For now, can you assign this issue to me (on github) as a reminder?

I've added you as collabrator and assigned the issue on you. One ask, please do not push anything without PR.

Thank you.

**Comment by TheCodeArtist** [comment]
Thanks. Now i will be extra-careful when doing `git push origin` :-)

Will get the first draft of writing-guidelines ready in a couple of days.

Meanwhile, do take a call on the capitalisation of files/directories across the entire repo.
My initial :+1: is for all small file/directory names (as is the norm on common unix filesystems).

**Comment by 0xAX** [comment]
@TheCodeArtist ok, will wait. Thank you.
