### ISSUE TITLE
should it be between the given `size` and `ULLONG_MAX - base`.

### ISSUE THREAD

**Issue by adjkldd** [0xAX/linux-insides#118]
Hi, I am translating your [Linux kernel memory management Part 1](https://github.com/0xAX/linux-insides/blob/master/mm/linux-mm-1.md) into Chinese.  In _Memblock API_ section after `memblock_cap_size` code block goes a sentence:
>`memblock_cap_size` returns new size which is the smallest value between the given `size` and base.

Should it be like the below?

>`memblock_cap_size` returns new size which is the smallest value between the given `size` and `ULLONG_MAX - base`.

**Comment by 0xAX** [comment]
Hello @adjkldd,

> Hi, I am translating your Linux kernel memory management Part 1 into Chinese

Very glad to hear it.

> Should it be like the below?....

Yes, thank you for this. I've just fixed it in the post.
