### ISSUE TITLE
[Theory/ELF.md]  "vmlinux.lds" file should be "arch/x86/kernel/vmlinux.lds.S"

### ISSUE THREAD

**Issue by a1ickgu0** [0xAX/linux-insides#120]
“arch/x86/kernel/vmlinux.lds” should be "arch/x86/kernel/vmlinux.lds.S" ?

**Comment by mudongliang** [comment]
I want to ask where is the vmlinux file? I search in the debian system and find nothing but vmlinuz in /boot directory.

**Comment by a1ickgu0** [comment]
linux-3.5.1 source: 
`arch/x86/kernel/vmlinux.lds.S`

**Comment by 0xAX** [comment]
@a1ickgu0 I see `vmlinux.*` only in two places in the `Theory/ELF.md`. The first is correct (155 line), the second `arch/x86/kernel/vmlinux.lds` - generated.  Did I miss something?

@mudongliang The `vmlinux` is a result of kernel building process. `vmlinuz` is just comppresd `vmlinux` and concatenated with the setup code. So, you can get it only if you will be the kernel by hand or extract it from `vmlinuz` with the https://github.com/torvalds/linux/blob/master/scripts/extract-vmlinux script.

**Comment by mudongliang** [comment]
Thank you very much @0xAX

**Comment by a1ickgu0** [comment]
@0xAX , yes, the second ``arch/x86/kernel/vmlinux.lds`` should be ``arch/x86/kernel/vmlinux.lds.S`` , right?

**Comment by 0xAX** [comment]
@a1ickgu0 sorry for delay.

>@0xAX , yes, the second arch/x86/kernel/vmlinux.lds should be arch/x86/kernel/vmlinux.lds.S , right? 

No, the second address of the linker script is correct. It is generated after compilation.
