### ISSUE TITLE
Advice needed

### ISSUE THREAD

**Issue by NateshR** [0xAX/linux-insides#124]
Hey, I was going through your post, they are really good. I want to hack android os, for that I read some kernel development books and build some small drivers and modules. but still I didn't have much confidence in it, so please guide me how to hack kernel drivers from the start.

**Comment by 0xAX** [comment]
@NateshR, Hello, sorry for the delay, just saw your issue. I'm not sure that I'm best person who can add any advices about drivers hacking, But did you look on the LDD 3?

**Comment by NateshR** [comment]
I have that book, but was thinking of practicing. What will you recommend, should I start exploring the book?

**Comment by amitsaha** [comment]
Have you thought about participating in the eudyptula challenge?

**Comment by NateshR** [comment]
I did, but it had some issue, so then I dropped it. I read book by robert love, I want to code in linux (driver,  system, or shell). I will explore LDD 3.
