### ISSUE TITLE
problem in ELF.md file

### ISSUE THREAD

**Issue by mudongliang** [0xAX/linux-insides#144]
In linux , there are three kinds of file in elf format:
- relocation file(object file)
- execute file
- shared object file

But in ELF.md file, you always say **"elf object file"**. I don't know your original meaning, but this word will lead us confusion.
Besides, you should add the **Linking View** and **Execution View**. This will help to classify those three kinds of file.

**Comment by 0xAX** [comment]
@mudongliang Yes, thank you, will fix it
