### ISSUE TITLE
Get someone to proof read linkers.md

### ISSUE THREAD

**Issue by AntonioCS** [0xAX/linux-insides#147]
This is an interesting subject but the grammatical errors are too much.
Examples of grammatical errors: 

* The nm util allows us to see the list of symbols from the given object file. Look on _the its_ output, it consists from the
* Here we _are interesting only_ in the two callq operations.

There are probably more but I just can't keep reading after things like this.

**Comment by 0xAX** [comment]
> There are probably more but I just can't keep reading after things like this.

It is not a probably, it is 100% more. If you see something wrong, feel free PR.

Thank you
