### ISSUE TITLE
Chinese Edition about this book?

### ISSUE THREAD

**Issue by mudongliang** [0xAX/linux-insides#169]
I think this book is very interesting and useful. So I want to translate it to Chinese and publish it in the gitbook as the english version.
In order to ensure my work is not done yet, I ask in the issue. 
Thank you all.

**Comment by 0xAX** [comment]
Hello,

@xinqui already started to do it (https://github.com/xinqiu/linux-insides), I think you can connect and do it with him.

**Comment by mudongliang** [comment]
Good. :+1:  
But I think it's better if we separate it to one repo!
