### ISSUE TITLE
Typo in SysCall/syscall-1.md

### ISSUE THREAD

**Issue by Anstow** [0xAX/linux-insides#196]
Should the line 302 in linux-insides/SysCall/syscall-1.md be:

    asmlinkage long sys_write(unsigned int fd, const char __user * buf, size_t count);

rather than:

    asmlinkage long sys_write(unsigned int fd, const char __user * filename, size_t count);

**Comment by 0xAX** [comment]
@Anstow Yes, right will fix it now.

Thank you.
