### ISSUE TITLE
0xffff0000:0xfff0 in protected mode is right?

### ISSUE THREAD

**Issue by mudongliang** [0xAX/linux-insides#197]
`CS` register consists of two parts: the visible segment selector and hidden base address. We know predefined `CS` base and `IP` value, so the logical address will be:

```
0xffff0000:0xfff0
```

According to protected mode, the logical address should be "0xffff:0xfff0", is it ?

**Comment by 0xAX** [comment]
@mudongliang Logical address consists from two parts: selector (from segment register) and offset (from `IP`), but if you're about the first address when a computer boot up it is not in protected mode. There is special mode which is very similar on real mode (more you can find in https://www.cs.cmu.edu/~410/doc/minimal_boot.pdf)

**Comment by mudongliang** [comment]
I have read the knowledge about booting before bios. The register value of CS, EIP is fixed. I don't find materials about this stage in your provided file.
Bios uses real mode for memory address.
After bios, linux use protected mode for memory address.

**Comment by 0xAX** [comment]
> After bios, linux use protected mode for memory address. 
It depends on bootloader, modern Linux kernel can be in real mode, protected mode or even long mode after bootloader will load and transfer control to the kernel
