### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by leolas95** [0xAX/linux-insides#200]
I didn't know whether to put this here or create a PR, so sorry if this isn't the right place. I would like to see a Spanish translation of the book. I've just started with the first chapter, so I would like to know if it would be ok and no one has a problem with it.

**Comment by 0xAX** [comment]
Hello @leolas95, just wrote about this in the #169. The better way to create separate repository and let me know about this, I'll add link to the README of main main repo.

Thank you.

**Comment by leolas95** [comment]
Ok, so I'll just fork it and start the translation. Thanks, and I will be notifying you with all the important things!
