### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by leolas95** [0xAX/linux-insides#202]
I have already started the spanish translation of the first post. It's going a bit slow, since I'm all by myself. I have put links to the original repo and author. However, in other things I've put links
to my email an twitter account, since it will be regarding the translation. I hope that everything is ok.

https://github.com/leolas95/linux-insides

**Comment by 0xAX** [comment]
@leolas95 Yes, it looks very good for me. I've added link to the Readme. Thank you.

**Comment by leolas95** [comment]
Ok, thank you!

**Comment by mudongliang** [comment]
I have an question about github fork.
I fork linux-insides( english version ), then if I fork linux-insides(chinese/spanish version), it only shows me the fork of linux-insides(english version).
So I think shall we separate the other languages to one independent repo?
