### ISSUE TITLE
a sentence need to be explained

### ISSUE THREAD

**Issue by mudongliang** [0xAX/linux-insides#211]
```
Here we can see the jump instruction opcode - 0xe9 to the address _start - ( . + 2),
 and we can see that the reset section is 16 bytes and starts at 0xfffffff0
```
This is one sentence from Booting/linux-bootstrap-1.md which I can't understand. Can someone explain it for me?

**Comment by 0xAX** [comment]
Hello @mudongliang, What's the problem with it? There is code of reset vector which must contain jump instruction. And here we can see it. The `0xe9` is opcode of 3 bytes jump, the `.int   _start - ( . + 2 )` expression expands to the `_start` address `-` (current address + 2 bytes), in other words we have 5 bytes jump here.

**Comment by mudongliang** [comment]
OK. The reset_vector is filled in "jmp addr". Just show in binary formats.
jmp  ->  "0xe9"
addr ->  "_start - ( . + 2 )"
Is it right?

**Comment by 0xAX** [comment]
Yes

**Comment by mudongliang** [comment]
Thanks for your explain. However, 

> we can see the jump instruction opcode - 0xe9 to the address _start - ( . + 2)

  this part has a syntax problem.

**Comment by 0xAX** [comment]
@mudongliang How can I fix it?

> we can see the jump instruction opcode - 0xe9 to the _start - ( . + 2) address? or in other words - `jmp _start - (. + 2)`

**Comment by mudongliang** [comment]
> we can see the jump opcode - 0xe9 and its destination address - `_start - ( . + 2) address`

Is it ok? Is this the same meaning with your sentence?

**Comment by 0xAX** [comment]
Yes, that's ok
