### ISSUE TITLE
How many kinds of List in Linux Kernel?

### ISSUE THREAD

**Issue by mudongliang** [0xAX/linux-insides#237]
I have found two kinds of list in kernel : list_head, and hlist_head. The former is for doubly linked list, and the latter is for hash. Is there any other list structure?

**Comment by 0xAX** [comment]
There are also [Lock-less linked list](https://github.com/torvalds/linux/blob/master/include/linux/llist.h), [priority-sorted double-linked list](https://github.com/torvalds/linux/blob/master/include/linux/plist.h)

**Comment by mudongliang** [comment]
Thank , @0xAX !
