### ISSUE TITLE
Stack setup numbering

### ISSUE THREAD

**Issue by jlacomis** [0xAX/linux-insides#278]
The numbering in Stack Setup under From Bootloader to Kernel is wrong. Instead of 1., 2., 3. it is 1., 1., 1.

**Comment by jlacomis** [comment]
It seems to be numbered correctly in the .md file, and renders correctly in the dillinger.io editor, but it is not rendering correctly on github.com or on gitbooks.io for me. (Chrome, OS X 10.11)

**Comment by 0xAX** [comment]
Fixed thanks
