### ISSUE TITLE
Question in the linux-bootstrap-1.md file

### ISSUE THREAD

**Issue by c02y** [0xAX/linux-insides#29]
You got 

    >>> hex((0x2000 << 4) + 0x0010)
    '0x20010'

how do you do that, it is a package for Emacs, or some program you can execute in terminal?

**Comment by arindamchoudhury** [comment]
looks like python prompt

**Comment by c02y** [comment]
Damn, I just figured it out by viewing the raw `linux-bootstrap-1.md` file, it says the source code snippet is in Python.

Why cannot I delete this issue post? Who can close this issue?

**Comment by 0xAX** [comment]
@c02y I close it
