### ISSUE TITLE
CS base, IP value, how logical address?

### ISSUE THREAD

**Issue by c02y** [0xAX/linux-insides#30]
> We know predefined CS base and IP value:

which is:

    IP          	0xfff0
    CS selector 	0xf000
    CS base        0xffff0000

> so our logical address will be:
> 0x0ffff000:0xfff0

How so?

**Comment by 0xAX** [comment]
@c02y: Ah, yes, now i understand. There is typo there, will fix it. Thank you.

**Comment by c02y** [comment]
Yeah, I guess so.
