### ISSUE TITLE
some questions about "Early page tables initialization"

### ISSUE THREAD

**Issue by hitmoon** [0xAX/linux-insides#303]
I read head_64.S and find when initialization level 3 (PDPE) entries, the flags are all 0x7, but you said: " where the first entry will be with 0x7 flags and the others with 0x8" , which I can not agreen. The same issue exists for level 2 (PDE) entries initialization. Can you give me a reasonable explanation ?
Thank you !

**Comment by 0xAX** [comment]
Hello @hitmoon,

Here is it

```assembly
    addl    $8, %edi
```

**Comment by hitmoon** [comment]
@0xAX：
As far as I know, the instruction:
addl     $8, %edi 
is used to update the target entry address (to write), where the data to write is stored in %eax !

**Comment by 0xAX** [comment]
Hello @hitmoon yes, you're fully right here. Fixed
