### ISSUE TITLE
阅读中遇到个问题，还望解答。

### ISSUE THREAD

**Issue by Joinhack** [0xAX/linux-insides#307]
我在阅读https://0xax.gitbooks.io/linux-insides/content/Booting/linux-bootstrap-1.html， 做测试我使用install_gdt中使用的代码如下：

void install_gdt() {
	static const u64 boot_gdt[] __attribute__((aligned(16))) = {
		0
	};
	static const struct gdt_ptr gdtptr = {
		.len = sizeof(boot_gdt),
		.ptr = (u32)boot_gdt
	};
	asm volatile ("lgdtl %0" : : "m"(gdtptr));
}
连接脚本如下：
SECTIONS
{
	. = 0;
	.text16 : {
		*(.text16)
	}
	c32_begin = .;
	.text32 : {
		*(.text32)
	}
	. = ALIGN(16);
	.rodata : { 
		*(.rodata*) 
	}
	.data : {
		*(.data)
	}
	.bss : {
		*(.bss)
	}
	/DISCARD/ : {
		*(.MIPS.options)
		*(.options)
		*(.pdr)
		*(.reginfo)
		*(.comment)
		*(.note)
	}
}

我的问题是 生成的代码 访问的是地址是从0x0开始链接的（这个当然是这么的因为	. = 0;指定了）， 但是我看linux的kernel 也是这么的 不晓得它是怎么让链接出来的地址能够和内存对应。

linux的链接接本https://github.com/torvalds/linux/blob/097f70b3c4d84ffccca15195bdfde3a37c0a7c0f/arch/x86/boot/setup.ld

**Comment by mudongliang** [comment]
这里是英文版，很多人不认识汉语。
This repo is for english, there are many contributors which don't know Chinese.

**Comment by Joinhack** [comment]
This issue can be fixed, I think I got the answer, thanks.

**Comment by mudongliang** [comment]
Please close this issue when you think you got the answer.
