### ISSUE TITLE
Chinese Edition Problems

### ISSUE THREAD

**Issue by mudongliang** [0xAX/linux-insides#312]
I am sorry about Chinese Edition for linux-insides is misoperated to delete by one administrator in my organization.
Now the link in README for Chinese Edition is broken. I was contacting with Github Help to solve this problem and tried to persuade Github to restore my organization.
Apologies!
If github can't restore my organization, I will redirect the link to another repository.
@0xAX

**Comment by 0xAX** [comment]
@marmeladema Let me know and I'll update link if need

**Comment by mudongliang** [comment]
It's OK! Github has helped me restore my organization and repositories. The repository is ok now! Nothing is needed to change. Sorry for the misoperation! @0xAX
