### ISSUE TITLE
Inlining, binary size

### ISSUE THREAD

**Issue by feribg** [0xAX/linux-insides#332]
Not sure about this part:

```
always inlined to reduce size of the Linux kernel image
```

Isn't it pretty much the other way around. If you inline a function many many times, it would actually increase the size of the resulting binaries, not decrease them.

**Comment by veddan** [comment]
It depends. For very small functions, the code required in the caller to make the call (ie. setting up arguments, saving caller-save registers and restoring them after the call) can be larger than the body of the function itself.
