### ISSUE TITLE
Inconsistency with kernel setup offset

### ISSUE THREAD

**Issue by doomrobo** [0xAX/linux-insides#37]
In linux-bootstrap-1, you say the offset of the actual kernel setup code is 0x200. But later in the document, you say `state.cs = segment + 0x20` not `0x200`. Also you write `cs = 0x1020` where it seems like it should be `cs = 0x10200`. Do I have something wrong or were you just missing a digit?

**Comment by 0xAX** [comment]
@doomrobo, Yes `segment` is `0x1000` and `state.cs = 0x1000 + 0x20 = 0x1020`. Kernel setup code loaded at `0x10200` (physical address, not `cs` value) because:

cs = 0x1020
ip  = 0x0000

Physical address will be:

```
(0x1020 << 4) + 0x0000 = 0x10200
```

Also about you PR #35, `X` it's offset from the start of memory

**Comment by doomrobo** [comment]
Understood. Thank you for the response!
