### ISSUE TITLE
Incorrect inline assembly example

### ISSUE THREAD

**Issue by Smattr** [0xAX/linux-insides#384]
Great [description of inline assembly](https://github.com/0xAX/linux-insides/blob/master/Theory/asm.md)! However, I think there is a typo in the discussion of more obscure constraints. The text contains the following:

> All of these constraints may be combined (of course actually not all of them). In this way the compiler will choose the best one for a given situation. For example:

The example that follows this does _not_ appear to demonstrate a combination of these constraints. In fact the example appears identical to the first example from the next section which makes me think it is the result of a copy-and-paste error. Is this a mistake? If this is intentional and I have misunderstood the example, apologies for the false positive.

**Comment by 0xAX** [comment]
@Smattr you're absolutely right. I will try to write better example

**Comment by 0xAX** [comment]
added better example to 3c83a2257aee4ba9b6ba08de1ead80bba51bd9d0
