### ISSUE TITLE
New formatting paramenters suggestion

### ISSUE THREAD

**Issue by alx741** [0xAX/linux-insides#42]
I would like to suggest some new formatting parameters:
- Fit lines in 80 chars width (now is infinite long lines).
- Beware of trailing whitespaces.

I've tried in this [branch](https://github.com/alx741/linux-insides/tree/formatting), but i've used automatic formatting and seems to be broken (bad backquotes handling).

Maybe some manual inspection or another autoformatting method would work.

**Comment by ttipat** [comment]
Good

**Comment by TheCodeArtist** [comment]
+ Sticking to a 80chars/line width would make reviewing diffs a whole lot easier. Right?
+ However ascii-art diagrams could be an allowed exception to this rule.

Also if we really plan to add manual line-breaks then
- Does the git-book version require any reformatting or looks good there too?
- How to convert existing test to 80char/line format? One huge commit?

**Comment by 0xAX** [comment]
> Sticking to a 80chars/line width would make reviewing diffs a whole lot easier. Right?
Right.

> However ascii-art diagrams could be an allowed exception to this rule.
Yes, some diagrams are too wide for 80 chars.

> Does the git-book version require any reformatting or looks good there too?
Do not know. And there is one reason I will not accept this: When I'm writing a part, I do not want to pay attention on a length of line, because there are many lines sometimes, and I'm rewriting many times one line. It need much time to follow this rule and I do not want to spend time on it.

**Comment by TheCodeArtist** [comment]
> When I'm writing a part, I do not want to pay attention on a length of line, because there are many lines sometimes, and I'm rewriting many times one line. It need much time to follow this rule and I do not want to spend time on it.

Correct. You should get your editor to automatically do it for you instead.

Searching for "vi hard wrap" will show you multiple ways to configure vim(my goto editor on Linux) to automatically insert new lines at a fixed width as you type (or even allow you to reformat a whole block of text you just typed in one shot later as well)

For notepad++ (my goto editor on Windows) there seem to be some roundabout ways like
http://superuser.com/questions/100010/how-can-a-paragraph-be-reformatted-in-notepad

**Comment by 0xAX** [comment]
@TheCodeArtist I'm using emacs :) No, of course it is not a problem to configure editor, but is there any reasons to use 80-chars besides better review?
