### ISSUE TITLE
Can't run boot code in linux-bootstrap-1

### ISSUE THREAD

**Issue by grapherd** [0xAX/linux-insides#423]
Hi everyone,

I'm trying to run boot code in linux-bootstrap-1
after trying this command
`nasm -f bin boot.nasm && qemu-system-x86_64 boot`

My qemu tell's me that it can't found a bootable device.

image: http://i.imgur.com/elNOZmz.png

how can I solve this problem?

thanks.

**Comment by 0xAX** [comment]
Hello @grapherd,

just tested it again and have no any problems.
