### ISSUE TITLE
Intel assebmly syntax in linker.md

### ISSUE THREAD

**Issue by mudongliang** [0xAX/linux-insides#428]
In Misc/linker.md, we use intel assembly syntax to show a hello world example. However, with the context, we should write this example with AT&T assembly syntax.

**Comment by mudongliang** [comment]
I have written a snippet in AT&T assembly semantics:

[test.S](https://gist.github.com/mudongliang/c3afd8ad9bcd4a27402771f19d2f4249)

**Comment by 0xAX** [comment]
Hello @mudongliang, looks good, will you submit PR?

**Comment by mudongliang** [comment]
Yes, I will

**Comment by 0xAX** [comment]
Thanks

**Comment by mudongliang** [comment]
PR : #429
