### ISSUE TITLE
Is it essential to change folder name "mm" to "MM"?

### ISSUE THREAD

**Issue by mudongliang** [0xAX/linux-insides#432]
In this repo, there are many folders, one folder for one chapter. However, the name of two folders(mm, interrupts) are not very suitable due to lower case.
Is it essential to change those two folds to "Interrupts" and "MM" to match the whole style of folder naming?

**Comment by 0xAX** [comment]
Hello @mudongliang 

>  Is it essential to change those two folds to "Interrupts" and "MM" to match the whole style of folder naming?

Yes

**Comment by mudongliang** [comment]
Got it
