### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by proninyaroslav** [0xAX/linux-insides#442]
Hello. I have already started the Russian translation of your posts. I'll translate posts in free time. I have put links to the original repo and author. Please add link to my repo in README

https://github.com/proninyaroslav/linux-insides-ru

I hope for further cooperation and wish you success in your valuable work.

**Comment by 0xAX** [comment]
Hey @proninyaroslav Thank you for your great work 👍. Will put link to your repo to README.

**Comment by 0xAX** [comment]
Updated README.md. Thank you again!
