### ISSUE TITLE
`lockdep_init()` doesn't exist anymore and chapter kernel entry point

### ISSUE THREAD

**Issue by Seraphime** [0xAX/linux-insides#448]
It was eliminated in 06bea3dbfe6a4c333c4333362c46bdf4d9e43504.

I know the book states explicitly it covers 3. something kernel, but I find the chapter really confusing as all the links point to the newest kernel and the `kernel_start` function look nothing like the chapter says today.

Maybe it is worth adding some sort of caveat, so readers don't get confused between kernel versions.

**Comment by 0xAX** [comment]
removed in https://github.com/0xAX/linux-insides/commit/df66966959869ce4228e3dae436bd9c0ddee22cf
