### ISSUE TITLE
"segement" typo?

### ISSUE THREAD

**Issue by fishilico** [0xAX/linux-insides#45]
Hi,
In the 3rd part of Kernel Booting Process, the word "segement" is used several times (for example on https://github.com/0xAX/linux-insides/commit/9707a443b93d10882feef60ceff9c6c9be4f6cca#diff-bd7a5d6000784eb76eabb976454db43bR364). As this word occurs several times, I wonder whether this is "segment" with a typo or a technical word which was not defined. If it is a typo, could you please fix it?
Thanks

**Comment by 0xAX** [comment]
Thank you @fishilico, it is already fixed by @akash0x53 in the previous PR
