### ISSUE TITLE
Wrong interpretation of hardcoded instruction

### ISSUE THREAD

**Issue by PinoTsao** [0xAX/linux-insides#464]
In "Kernel booting process. Part 1" - "From the bootloader to the kernel", there is following paragraph:

_Here we can see a jmp instruction opcode (0xeb) that jumps to the start_of_setup-1f point. In Nf notation, 2f refers to the following local 2: label; in our case, it is label 1 that is present right after jump, and it contains the rest of the setup header. Right after the setup header, we see the .entrytext section, which starts at the start_of_setup label._

I think it is wrong, look at the code:
	.globl	_start
_start:
		# Explicitly enter this as bytes, or the assembler
		# tries to generate a 3-byte jump here, which causes
		# everything else to push off to the wrong offset.
		.byte	0xeb		# short (2-byte) jump
		.byte	start_of_setup-1f
1:

I think it is hardcoded **jmp** instruction. Look at the syntax interpretation:
http://tigcc.ticalc.org/doc/gnuasm.html#SEC75
http://tigcc.ticalc.org/doc/gnuasm.html#SEC62
"start_of_setup-1f" should just be a Integer expression, not jump to label in the front

**Comment by 0xAX** [comment]
>  "start_of_setup-1f" should just be a Integer expression, not jump to label in the front

Actually yes. I meant here that `1f` is address of the next instruction, of course yes it is part of arithmetic expression which results in integer.

**Comment by PinoTsao** [comment]
Oh, I think I am aware where I am wrong. You are right, sorry for the false positive.
