### ISSUE TITLE
IDT diagram error?

### ISSUE THREAD

**Issue by Pawel-Junak** [0xAX/linux-insides#467]
hey,

in linux-insides/Initialization/linux-initialization-2.md
not sure if IDT diagram is ok?
15 and 16 bit order swaped in first line,
also 'Offset' and 'Segmetn Selector' tags.

greets

**Comment by 0xAX** [comment]
Thanks @Pawel-Junak, will check this

**Comment by 0xAX** [comment]
Fixed in 1a15aeda5ad077a044697a3b4eee6cbec08875d3
