### ISSUE TITLE
Why do we need to get the real physical address of the startup_32?

### ISSUE THREAD

**Issue by hao-lee** [0xAX/linux-insides#478]
Hi,

In [this piece of code](https://github.com/torvalds/linux/blob/42e1b14b6e1455ece2ccbe474c25388d0230a590/arch/x86/boot/compressed/head_64.S#L76-L79), we use a short local call to get the real physical address of the `startup_32`:

```
	leal	(BP_scratch+4)(%esi), %esp
	call	1f
1:	popl	%ebp
	subl	$1b, %ebp
```

However, I think this calculation may not be necessary. We use `jmpl	*%eax` to jump to `startup_32` and the value of `eax` is `0x100000`, so it's no doubt that the physical address of `startup_32` is `0x100000`. Besides, the result of this piece of code is also `0x100000` and it seems that this calculation is meaningless. Could someone give me some hints about why we need to do so? Many Thanks!

**Comment by 0xAX** [comment]
> We use jmpl *%eax to jump to startup_32 and the value of eax is 0x100000

Linux kernel is relocatable and the load address can be another besides `0x100000`
