### ISSUE TITLE
Mention header linker script along with `header.S`

### ISSUE THREAD

**Issue by Aaron1011** [0xAX/linux-insides#479]
The file [arch/x86/boot/header.S](https://github.com/torvalds/linux/blob/master/arch/x86/boot/header.S) contains many other parts besides the `hdr` symbol. Mentioning [the linker script](https://github.com/torvalds/linux/blob/249f1efd8e3d58f86469fc305b0eda39db18d7ce/arch/x86/boot/setup.ld#L17) can help make it clear that the `.header` section (and `hdr` symbol) are what actually get placed at offset `0x01f1`.

**Comment by 0xAX** [comment]
Hello @Aaron1011, thanks for suggestion. pushed in https://github.com/0xAX/linux-insides/commit/12006725a4de652d9579e8524de4ebfe2fba6c1e

**Comment by Aaron1011** [comment]
Thanks! :)
