### ISSUE TITLE
Probably mistakes in linux-bootstrap-1.md

### ISSUE THREAD

**Issue by litao91** [0xAX/linux-insides#494]
In the section **start of kernel setup**, I believe that the segments should have the following value after kernel setup starts:

```c
gs = fs = es = ds = ss = 0x10000
cs = 0x10200
```

Similarly, in the **Segment register align** section, it should be 

grub2 loads kernel setup code at address `0x10000` by default and cs at `0x10200` because execution doesn't start from the start of file, but from:

**Comment by 0xAX** [comment]
should be fixed now. thank you.
