### ISSUE TITLE
A doubt about line 79 of syscall-1.md

### ISSUE THREAD

**Issue by WarpspeedSCP** [0xAX/linux-insides#502]
What does 
> and we are initializing `syscalls` by the writing of the `entry_SYSCALL_64`

Mean? 

`entry_SYSCALL_64` isn't a variable, right?

please explain this sentance.

**Comment by faj25** [comment]
I think 'writing of the' can be replaced by 'use of.' It need proofreading, if you'd like to give it a shot.

**Comment by WarpspeedSCP** [comment]
Well, I'm editing the syscall section and correcting grammar mistakes. I'll soon be doing a pr.

**Comment by 0xAX** [comment]
I think the issue can be closed, as there is no such text anymore
