### ISSUE TITLE
 the reset vector

### ISSUE THREAD

**Issue by bicepjai** [0xAX/linux-insides#52]
you are saying the reset vector is 
> FFFF0000h:FFF0h

then add it as its segmented address
> 0xffff0000 + 0xfff0
'0xfffffff0'

according to your definition, to get linear address from segmented address, we need to multiple by 16 or left shit 4 and then add the offset right ? should it be

> FFFFF000h:FFF0h

in real mode as explained in the 
wiki page http://en.wikipedia.org/wiki/Reset_vector

**Comment by 0xAX** [comment]
Hello @bicepjai,

all is correct. Physical address is:

```
0xffff0000 + 0xfff0
'0xfffffff0'
```
which is 4gb - 16 bytes. We no need to shift base, it's post-shifting here. 

Also you can see in wiki that there is `0xfffff000` base of segment, seems that high `F` is just sign-expansion.
