### ISSUE TITLE
Syscall chapter

### ISSUE THREAD

**Issue by tejv** [0xAX/linux-insides#529]
I am learning linux internals. Please bear with me if I ask silly question.

Please elaborate on x86 does syscall happens in interrupt context.

I could not understand this. Once int 0x80 is run. It raises an interrupt which calls syscall handler.
1. So entire syscall runs in this interrupt context ? If yes is it enabling interrupts for scheduler , then if context switch happens cpu will again come back to this interrupt because it is not over yet. 

2. When user space to kernel space stack switch happens. This kernel stack is process kernel stack 
or kernel's stack ?

**Comment by 0xAX** [comment]
> So entire syscall runs in this interrupt context ? If yes is it enabling interrupts for scheduler , then if context switch happens cpu will again come back to this interrupt because it is not over yet.

I'm not sure about `interupt context` in a case of system calls, but yes. Consider long-runnning system call, like reading of a file or something like this. In this case the kernel may mark caller as blocked, save it context and run another process which is ready to run.

> When user space to kernel space stack switch happens. 

I think it is here https://github.com/torvalds/linux/blob/master/arch/x86/entry/entry_64.S#L146.

> This kernel stack is process kernel stack or kernel's stack ?

Each process (`thread_struct`) has kernel/user stack. In this case this is process's kernel stack.
