### ISSUE TITLE
Suggestions: Assembly Syntax and Boot Sector Disassembly

### ISSUE THREAD

**Issue by gsbabil** [0xAX/linux-insides#53]
Hi @0xAX,
thanks for your articles. Please find my two cents below:

 - Although in the "Required Knowledge" section we are starting by saying *"Understanding assembly code (AT&T syntax)"*, most of the assembly code at least in [linux-bootstrap-1.md](https://github.com/0xAX/linux-insides/blob/master/Booting/linux-bootstrap-1.md) is in Intel syntax. I think you should consider mentioning both Intel and AT&T given that if not more, Intel syntax is at least as commonly used as the AT&T syntax.

 - Here's a quick `objdump` command that you might consider adding to the article so that a curious reader can dump the compiled `boot` from `boot.nasm`, or an existing boot-sector from a running machine after having extracted the first 512 bytes using `dd`.

```shell
nasm -f binary boot.nasm
objdump -D -b binary -mi386 -Maddr16,data16,intel boot
```
Or,
```shell
dd if=/dev/sdaX of=boot bs=512 count=1
objdump -D -b binary -mi386 -Maddr16,data16,intel boot
```

**Comment by 0xAX** [comment]
@gsbabil yes, great suggestions, thank you for. 

I will add it in the nearest time

**Comment by 0xAX** [comment]
@gsbabil added.

Thank you for suggestions
