### ISSUE TITLE
About %rsp register at the beginning of function

### ISSUE THREAD

**Issue by jbgg** [0xAX/linux-insides#530]
Firstly, I apologize because this is not about the book, but it is the first reference of the book (here: https://0xax.gitbooks.io/linux-insides/content/Booting/linux-bootstrap-1.html).
The reference goes to https://0xax.github.io/categories/assembler/, and there is a entry about the layout of the stack frame (here: https://0xax.github.io/stack_layout_x86_64/).
This post says that %rsp (at the beginning of function) will point to %rbp-8. But with the instructions:
push %rbp
mov %rsp, %rbp
The stack pointer will be equal to %rbp.
Maybe the header instructions of the function is different, then it should be specified.

**Comment by 0xAX** [comment]
@jbgg you're right. `rsp` should point to the last local variable. Thanks for noting. I will fix this

**Comment by 0xAX** [comment]
updated now
