### ISSUE TITLE
When does the kernel initialize the final 4-level page tables?

### ISSUE THREAD

**Issue by hao-lee** [0xAX/linux-insides#536]
I'm currently reading [First steps in the kernel code](https://0xax.gitbooks.io/linux-insides/content/Initialization/linux-initialization-1.html). In this part, the kernel builds 4-level page tables, but it only uses `PGD`, `PUD` and `PMD`. I don't see any code that handles `Page Table Entry`, so only three levels are used and the page size is `2-MByte`. However, the real page size should be `4-KByte`, so I think the kernel will build some new 4-level page tables later. I have no idea when the kernel initializes these final 4-level page tables. Could you give me some hints? Thanks!

**Comment by 0xAX** [comment]
Linux kernel initializes non-early 4-level page table later, during initialization steps. You can start your research from the https://github.com/torvalds/linux/blob/master/init/main.c#L569
