### ISSUE TITLE
Why does the kernel need to set GDT in 64-bit mode?

### ISSUE THREAD

**Issue by hao-lee** [0xAX/linux-insides#541]
In [Kernel initialization. Part 1](https://github.com/0xAX/linux-insides/blob/master/Initialization/linux-initialization-1.md), kernel sets GDT before jumping to the C code, but I don't know why there is need to set GDT in 64-bit mode. I find this sentence in [Intel 64 and IA-32 Architectures Developer's Manual: Vol. 3A](https://www.intel.com/content/www/us/en/architecture-and-technology/64-ia-32-architectures-software-developer-vol-3a-part-1-manual.html):
> Section 3.2.4
> In 64-bit mode, segmentation is generally (but not completely) disabled, creating a flat 64-bit linear-address space. The processor treats the segment base of CS, DS, ES, SS as zero, creating a linear address that is equal to the effective address. The FS and GS segments are exceptions.

It seems that the segment base of CS is treated as zero and we can ignore it.

**Comment by 0xAX** [comment]
I see at least two reasons. 

The first there is initialization of `per-cpu` gdt(s), at least for bootstrap CPU during early initialization. 

The second is different set of segments. Look at the boot-time gdt http://elixir.free-electrons.com/linux/v4.14-rc8/source/arch/x86/boot/pm.c#L70 and the later on - http://elixir.free-electrons.com/linux/v4.14-rc8/source/arch/x86/kernel/cpu/common.c#L153 and that's why:

```assembly
	/*
	 * We must switch to a new descriptor in kernel space for the GDT
	 * because soon the kernel won't have access anymore to the userspace
	 * addresses where we're currently running on. We have to do that here
	 * because in 32bit we couldn't load a 64bit linear address.
	 */
	lgdt	early_gdt_descr(%rip)
```

> It seems that the segment base of CS is treated as zero and we can ignore it.

yes, but FS and GS are continue to be used

**Comment by hao-lee** [comment]
The comments above says:

> soon the kernel won't have access anymore to the userspace addresses where we're currently running on.

I can't understand this. Could you explain it, thanks!

**Comment by 0xAX** [comment]
> soon the kernel won't have access anymore to the userspace addresses where we're currently running on.

I'm not sure here, but seems this means that kernel code will be located in high addresses always, above userspace. Look at the descriptors in a case of `early_gdt_descr`, they differs in `dpl` and so on.

**Comment by hao-lee** [comment]
Thanks, I will keep exploring these details and I will comment there again if I find something new.
