### ISSUE TITLE
Are the virtual address and the linear address the same thing?

### ISSUE THREAD

**Issue by hao-lee** [0xAX/linux-insides#543]
In Linux kernel, one of the most common concepts is the `virtual address`. We can know from code comments or other kernel books that the virtual address can be translated to the physical address using pagetables.

However, the terminology `virtual address` confuses me because it is not used by Intel Manual.

In Intel Developer's Manual Volume 3A, `CS:EIP` is the logical address. It can be translated to the linear address by segmentation mechanism. The linear address then can be translated to the physical address by paging mechanism. This translation process is very clear, but where is the virtual address? The Intel Manual doesn't use the virtual address as a keyword to explain the memory mechanism, so I'm very confused.

Now I have a conjecture. I think the virtual address and the linear address are the same thing.
 Am I right? Thanks!

**Comment by 0xAX** [comment]
Hello @hao-lee,

> In Intel Developer's Manual Volume 3A, CS:EIP is the logical address. It can be translated to the linear address by segmentation mechanism. The linear address then can be translated to the physical address by paging mechanism. 

Right.

> This translation process is very clear, but where is the virtual address?

`linear` is `virtual` in x86_64 where segmentation is not used, i.e. there is no segment mapping of addresses mostly. So, `linear` may be considered here just as non-segmented

**Comment by hao-lee** [comment]
For Intel x86 32bit system, many materials treat `virtual address` as a alias of `linear address` while the others think `virtual address` is the alias of `logical address`. These terms may not interfere the understanding of linux kernel, but I still want to find out their relation.

**Comment by hao-lee** [comment]
Hi, @0xAX 
Finally, I believe the `virtual address` is the kernel term while the `linear address` is the Intel term. Reference is [here](https://linux-mm.org/VirtualMemory).

> In Intel documents, the term virtual address, as used in the kernel code, is replaced with linear address.
