### ISSUE TITLE
How to examine the value of registers?

### ISSUE THREAD

**Issue by firogh** [0xAX/linux-insides#549]
In Kernel booting process. Part 4.Transition to 64-bit mode, **Let's make sure that it is true by looking at the register values at the 32-bit entry point:**.
Could you please tell me the means you used to look at the registers?

**Comment by 0xAX** [comment]
Hello @firogh, If I remember correctly, I've just runned kernel in qemu virtual machine with `-s -S` command line arguments, connected to it with gdb debugger and set breakpoint at `0x10000` or something like this

**Comment by firogh** [comment]
@0xAX Cool! Thank you.
