### ISSUE TITLE
Discuss of standard filename conversion

### ISSUE THREAD

**Issue by mudongliang** [0xAX/linux-insides#568]
As there are many URLs in markdown files related with the standard filename conversion, if you change the filename of some files, we need to check whether there are some URLs related with this filename and modify it. This is very disgusting.

Could we directly uniform the standard filename conversion in the issue so I could maintain the filename of markdown files in my Chinese translation repo?

**Comment by 0xAX** [comment]
Hello @mudongliang, the file names should be unified now after https://github.com/0xAX/linux-insides/commit/6d69c2431baa928987366f906357205c552398d5

**Comment by mudongliang** [comment]
I agree with current filename convention. I wonder whether we should modify the folder names in our repo.

**Comment by mudongliang** [comment]
I saw you have fixed all the links inside the markdown files. That's cool. I will try to modify those urls following your commits.

**Comment by mudongliang** [comment]
In my [Chinese Translation Repo](https://github.com/MintCN/linux-insides-zh). I have modified: 

- "mm" -> "MM";
- "interrupts" -> "Interrupts";

I will appreciate it if you could accept those changes. It looks wired when you "mm", "interrupts" in the root directory of our repo. However, it will takes more time to fix URLs with those folder names. :(

**Comment by 0xAX** [comment]
@mudongliang I agree. 

> 
    "mm" -> "MM";
    "interrupts" -> "Interrupts";

That  looks pretty good and consistent with the naming of other root directories.

**Comment by mudongliang** [comment]
I will create one PR to do that job. As to searching the wrong URLs due to changes of folder name, I will try my best to take care of it at first. I have written one simple python script to automatically detect this kind of problem.

**Comment by mudongliang** [comment]
#575

**Comment by 0xAX** [comment]
> I will create one PR to do that job
oh, thank you, I will look

**Comment by 0xAX** [comment]
@mudongliang I've pushed your PR for now, thank you. Can you push your script to repo and I will do a check for other links

**Comment by mudongliang** [comment]
Sure.
