### ISSUE TITLE
Best approach to fix grammar nits ??

### ISSUE THREAD

**Issue by atishp04** [0xAX/linux-insides#569]
This is just minor nit-pick grammar issue on the page:
Timers/linux-timers-3.md
Section: The tick broadcast framework
"We already know that such timers called clock events devices in the Linux kernel. **Besides clock events devices.** Actually, each processor in the system has its own local timer which is programmed to issue interrupt at the time of the next deferred task. "

What is the best approach to raise/fix these issues ?  

Comment in gitbook or just send a pull request ?

**Comment by 0xAX** [comment]
Hello @atishp04, sorry for delay.

> What is the best approach to raise/fix these issues ?
    Comment in gitbook or just send a pull request ?

Feel free to send a PR.

Thank you

**Comment by 0xAX** [comment]
Fixed in https://github.com/0xAX/linux-insides/commit/5f1a9948ba5bc770b040af5ebabf33023492929c
