### ISSUE TITLE
One calculation issue in inline assembling examples

### ISSUE THREAD

**Issue by mudongliang** [0xAX/linux-insides#570]
```C
0000000000400400 <main>:
  ...
  ...
  ...
  4004fe:       48 c7 45 f8 05 00 00    movq   $0x5,-0x8(%rbp)
  400506:       48 c7 45 f0 0a 00 00    movq   $0xa,-0x10(%rbp)

  400516:       48 8b 55 f8             mov    -0x8(%rbp),%rdx
  40051a:       48 8b 45 f0             mov    -0x10(%rbp),%rax

  40051e:       48 c7 c2 64 00 00 00    mov    $0x64,%rdx
  400525:       48 01 d0                add    %rdx,%rax
```

we will see that the `%rdx` register is overwritten with `0x64` or `100` and the result will be ~~`115`~~ instead of `15`.

**115** looks not right. In `40051e`, new `rdx` overwrites the previous `rdx` value with "0x64", and `rax` value is 0xa. So after `add` instruction, the `rdx` value will be `0x64+0xa = 0x6e`, **110 (in decimal)**.

**Comment by 0xAX** [comment]
you're right. Don't know where I got `115` and `15`

**Comment by 0xAX** [comment]
It should be fixed in https://github.com/0xAX/linux-insides/commit/41c8f09c8e9cc325c3eed9e8e6feeee9b22d105a

**Comment by mudongliang** [comment]
Reopen it. Because you modified **15** to **10**. The right result is **15** other than **10**. :-1:
