### ISSUE TITLE
Simple tools to verify URL in markdown file is live or not

### ISSUE THREAD

**Issue by mudongliang** [0xAX/linux-insides#572]
Yesterday, in order to check wrong URLs in the **linux-insides-zh - the Chinese translation repo**, I wrote a python script to automatically detect do it.

Please see details in [markdown_scripts](https://github.com/MintCN/markdown_scripts)

@0xAX , you could try it and detect wrong URLs automatically. If you find any bug, please let me know.

**Comment by mudongliang** [comment]
I list the result of my tool in [my Gist](https://gist.github.com/mudongliang/8f122734b53e09beb57a3426fad07d30).
There should be some false positives in my tool, but it is still useful.

**Comment by 0xAX** [comment]
Thank you @mudongliang. Btw can you push PR with your script into this repo please, to `scripts/` directory or something like this

**Comment by mudongliang** [comment]
sure
