### ISSUE TITLE
[WIP] Korean version

### ISSUE THREAD

**Issue by mingrammer** [0xAX/linux-insides#578]
I'm translating this docs. When done, I'll send a PR for that.

**Comment by 0xF0D0** [comment]
저는 혼자 취미로 조금씩 번역하고 있었는데 100% 다하신건가요?

보니까 포크에는 아무 커밋도 안올라와있어서요. 관심이 있어서 코멘트 남깁니당

혹시라도 관심있으시면 @mingrammer 님 포크에서 작업해도 괜찮구요!

**Comment by mingrammer** [comment]
@0xF0D0 안녕하세요. 아뇨 저는 이제 막 시작 단계입니다 ㅎㅎ 이미 하고 계신분이 있었군요!

**Comment by 0xAX** [comment]
Hello @mingrammer. Thank you. 

> I'm translating this docs. When done, I'll send a PR for that.

yeah. Send a link to your repo in PR when you'll be ready and I will add to README.md

**Comment by 0xAX** [comment]
@mingrammer I'm going to close this issue, feel free to reopen it if you will have any questions or the link with translation so I will put it to README.md

**Comment by junsooo** [comment]
@mingrammer @0xF0D0  안녕하세요, 제가 이 이슈를 발견하지 못하고 5일전에 이 repo에 pull request를 보내서 readme에 한국어 버전을 추가하였습니다. 혹시 관심이 있으시면 답신 부탁드립니다. 저는 어디 포크에서 작업하든지 상관은 없습니다.

**Comment by mingrammer** [comment]
@0xF0D0 저는 우선 @junsooo 님 포크에서 작업을 진행하기로 했습니다
