### ISSUE TITLE
A small mistake about DMI 

### ISSUE THREAD

**Issue by kele1997** [0xAX/linux-insides#584]
I notice that in [Initialization/linux-initialization-5.md](https://github.com/0xAX/linux-insides/blob/master/Initialization/linux-initialization-5.md)，in `Conclusion` part,the `direct Media Interface scanning` words,and in [Initialization/linux-initialization-6.md](https://github.com/0xAX/linux-insides/blob/master/Initialization/linux-initialization-6.md),I found the `DMI scanning ` words.But when I try to open the [source code](https://github.com/torvalds/linux/blob/16f73eb02d7e1765ccab3d2018e0bd98eb93d973/drivers/firmware/dmi_scan.c) in the article,I found something in comment:  
```
/*
 * DMI stands for "Desktop Management Interface".  It is part
 * of and an antecedent to, SMBIOS, which stands for System
 * Management BIOS.  See further: http://www.dmtf.org/standards
 */
```   
and when I try to search it on wikipedia,I found that:    
```
Desktop Management Interface
From Wikipedia, the free encyclopedia
Not to be confused with SMBIOS or Direct Media Interface.
The Desktop Management Interface (DMI) generates....
```
so the `direct Media Interface scanning` should by modified to `Desktop Management Interface`

Sorry for my poor English,thank you for reading it

**Comment by 0xAX** [comment]
Hello @kele1997, thank you for issue. Nice catch. It must be fixed https://github.com/0xAX/linux-insides/commit/9679dbdd91bab643019becc2089b5f47a91218e9
