### ISSUE TITLE
About learning the latest kernel source code

### ISSUE THREAD

**Issue by hao-lee** [0xAX/linux-insides#585]
I want to know how many people are trying to understand the latest kernel source code. I have many questions but I don't know where to ask them. kernelnewbies mailing list is just a place to discuss general questions. If you ask details about some concrete code in `kernelnewbies@kernelnewbies.org`, you may not get any replies. How do you learn the source code of a subsystem, especially when you encounter problems?

**Comment by coderall** [comment]
the latest kernel has so many lines source code,you may want to learn part of it.So you could concentrate one or two key subsystem of it ,such as mm management,TCP
when you meet some questions , lwn.net is a good website.
at last,you'd better to master the 2.6.x kernel and then learn some higher version code.

**Comment by hao-lee** [comment]
@coderall I'm concentrating mm subsystem and I have read the 2.6 source code. However, the code in 2.6 is very different to 4.x, so I encounter many problems... :joy:

**Comment by coderall** [comment]
The hardware architecture is moving forward and kernel should make some changes to take best use of them,so you will feel it's apparently different.
in my opinion,you can search the new paper from VLDB、SOSP、OSDI and so on.

**Comment by hao-lee** [comment]
I often get stuck on some functions and don't know what they do. I hope I can find a place to discuss kernel code instead of kernel theory. @0xAX Hi, do you have the intention to build a community based on Linux-Insides to discuss the latest kernel?

**Comment by mudongliang** [comment]
@hao-lee I think this is a good idea.

**Comment by 0xAX** [comment]
Hello everyone,

> How do you learn the source code of a subsystem, especially when you encounter problems?

Trying to understand context around related function/data structure and etc... Asking author of the code via email.

> do you have the intention to build a community based on Linux-Insides to discuss the latest kernel?

Yes, maybe. But I'm not sure about format. how do you see it?

**Comment by hao-lee** [comment]
@0xAX I think a mailing list may be a good way to communicate, such as Google Group.

**Comment by hao-lee** [comment]
@rikvanriel Hi, could you create a mailing list called "KernelHacking" on kernelnewbies.org for us to discuss something related to kernel source code and this e-book?

**Comment by hao-lee** [comment]
@0xAX Hi, I create a Google Group [mailing list](https://groups.google.com/forum/#!forum/kernelhacking) to discuss the latest kernel source code. linux-insides is a good starting point to dive into the kernel code, so I think we can use this mailing list as a place to learn kernel together. I can create a pull request to add the list address and some descriptions to the README.md if you agree.

**Comment by hao-lee** [comment]
Close this issue because a [mailing list](https://github.com/0xAX/linux-insides#mailing-list) has been created for discussion.
