### ISSUE TITLE
question about a20_test

### ISSUE THREAD

**Issue by PinoTsao** [0xAX/linux-insides#586]
In chaper "Video mode initialization and transition to protected mode", there is following sentence about a20_test:

"Next, we write an updated ctr value into fs:gs with the wrfs32 function, ..."

It is describing the code "wrfs32(++ctr, A20_TEST_ADDR);"  if I don't miss anything. But, I don't see how could we know it is written into fs:gs? Doesn't the code just write the updated value into the same address where we have read, which is fs: A20_TEST_ADDR

**Comment by 0xAX** [comment]
this should be fixed in https://github.com/0xAX/linux-insides/commit/98ba56ad890366d38568a83b3ed95ee510d7f4c1

**Comment by 0xAX** [comment]
Thank you @PinoTsao
