### ISSUE TITLE
question about protected_mode_jump

### ISSUE THREAD

**Issue by PinoTsao** [0xAX/linux-insides#587]
In Kernel booting process. Part 3. section "Actual transition into protected mode", there is following:

First of all, we put the address of boot_params in the esi register and the address of the code segment register cs (0x1000) in bx

I want to know, how we are so sure about the value of cs is 0x1000? As Documentation/x86/boot.txt illustrate, the address of boot sector & kernel setup code is marked as "X", which is a grub allocated address, in grub code, it is the variable grub_linux_real_target hold the address value.

**Comment by 0xAX** [comment]
Hello, 

> I want to know, how we are so sure about the value of cs is 0x1000?

You're right here. The address should not necessary to be  `0x1000` for all cases. I've write this address because I've got it in my test in virtual machine (as I described in the first part), but yes, it needs to be clarified.

**Comment by 0xAX** [comment]
I've updated this
