### ISSUE TITLE
Sugguestion: command -> instruction?

### ISSUE THREAD

**Issue by PinoTsao** [0xAX/linux-insides#588]
In Kernel booting process. Part 4. section "Calculate relocation address": 

When we are using position-independent code an address is obtained by adding the address field of the command and the value of the program counter.

I think the term "command" is confusing, while "instruction" is appropriate, because the address field is embedded in the "instruction", not a command.

**Comment by mudongliang** [comment]
agree

**Comment by 0xAX** [comment]
:+1: will update soon

**Comment by 0xAX** [comment]
https://github.com/0xAX/linux-insides/commit/4df08a04e1e97c9c6870fef5101419e316e91717
