### ISSUE TITLE
What does "MBZ" stand for?

### ISSUE THREAD

**Issue by PinoTsao** [0xAX/linux-insides#590]
Hi,
In section "Early page table initialization", there is following description:

Here we do almost the same as in the previous example, all entries will be with flags - $0x00000183 - PRESENT + WRITE + MBZ. In the end, we will have 2048 pages with 2-MByte page or:

I don't find introduction of "MBZ" anywhere, as I understand, the "1" in flags 0x183 means CR4.PGE = 1 in  Table 4-17. Format of an IA-32e Page-Directory Entry that Maps a 2-MByte Page of Intel manual.

Could anyone leave a hint?

**Comment by 0xAX** [comment]
`must be zero` I think

**Comment by PinoTsao** [comment]
Thanks a lot:) @0xAX
