### ISSUE TITLE
Suggestion: improve a sentence

### ISSUE THREAD

**Issue by PinoTsao** [0xAX/linux-insides#593]
In Kernel booting process. Part 6, section "Physical address randomization", the following sentence does make me pauses for a while and read it many times to get its meaning:

The kernel decompressor should select random index of this array and it will be random place where kernel will be decompressed.

How about:
KASLR will select a random index of this array for kernel to be decompressed.

**Comment by 0xAX** [comment]
Maybe better will be:

> KASLR will select a random index of this array and the kernel will be decompressed to selected memory region

or something like this?

**Comment by 0xAX** [comment]
https://github.com/0xAX/linux-insides/commit/efed15d860e091133903ae834c686524b0150e8f
