### ISSUE TITLE
Minor spelling correction

### ISSUE THREAD

**Issue by unixbhaskar** [0xAX/linux-insides#595]
ON this page: https://0xax.gitbooks.io/linux-insides/content/Booting/linux-bootstrap-1.html

Go to Jump main section and there is a little typo ...

Instead of Call, it is showing Calll (three L) :)

**Comment by 0xAX** [comment]
Hello @unixbhaskar, thank you but it is not a typo, see https://github.com/0xAX/linux-insides/issues?utf8=%E2%9C%93&q=calll
