### ISSUE TITLE
set_bios_mode seems to be called before memory detection

### ISSUE THREAD

**Issue by yourpleasure** [0xAX/linux-insides#596]
In [main.c](https://github.com/torvalds/linux/blob/16f73eb02d7e1765ccab3d2018e0bd98eb93d973/arch/x86/boot/main.c#L155), I can see that set_bios_mode is called before detect_memory. But in Chapter `Booting` Section `First steps in the kernel setup code` [Booting/linux-bootstrap-2.md](https://github.com/0xAX/linux-insides/blob/master/Booting/linux-bootstrap-2.md#memory-detection) , you say `Next, we may see a call to the set_bios_mode function` after introduce detect_memory. I wonder if there may be some mistake.

**Comment by 0xAX** [comment]
Hello @yourpleasure, thank you, it should be fixed in https://github.com/0xAX/linux-insides/commit/b4f824db27afae3626d0beb096ac8e3172831145
