### ISSUE TITLE
Question about calculating IP after CPU reset?

### ISSUE THREAD

**Issue by jxl4650152** [0xAX/linux-insides#618]
Hey, guys,
From Section _from bootloader to kernel_ of Chapter _booting_, we know that, after CPU reset, the EIP is calculated by adding CS base to IP.  But as the other part of this section says, the formulation should be  EIP = CS selector + IP.  Is this an exception or did I misunderstand the description. 
Thank you.

**Comment by tkyymmt** [comment]
Hello @jxl4650152 
I think it's just exception.
Calculating EIP during hardware resetting (i.e. calculating reset vector) seems different from calculating IP 
in real mode somehow.
[This](https://stackoverflow.com/questions/23422594/reset-vector-in-386-processors) may helps your insight.

**Comment by PinoTsao** [comment]
The real operation of calculating is take the value of base address of hidden part of segment register, add it to the IP(offset). Every time cs is loaded, the value of hidden part will be refreshed. Look at chapter 3.4.3 of Intel software developer manual 3A

**Comment by DamianFekete** [comment]
From https://www.amd.com/system/files/TechDocs/24593.pdf

> 14.1.5 Fetching the First Instruction
>
> After a RESET or INIT, the processor is operating in 16-bit real mode. **Normally** within real mode, the code-segment **base-address** is formed by **shifting the CS-selector value left four bits**. **The base address is then added to the value in EIP** to form the physical address into memory. As a result, the processor can only address the first 1 Mbyte of memory when in real mode.
> 
> **However**, immediately following RESET or INIT, the CS-selector register is loaded with F000h, but
> **the CS base-address is not formed by left-shifting the selector**. Instead, **the CS base-address is
> initialized to FFFF_0000h**. EIP is initialized to FFF0h. Therefore, the first instruction fetched from
> memory is located at physical-address FFFF_FFF0h (FFFF_0000h + 0000_FFF0h).
> 
> **The CS base-address remains at this initial value until the CS-selector register is loaded by software**.
> This can occur as a result of executing a far jump instruction or call instruction, for example. When CS
> is loaded by software, the new base-address value is established as defined for real mode (by left
> shifting the selector value four bits).

(emphasis mine)

**Comment by 0xAX** [comment]
I assume this one could be closed. @jxl4650152 feel free to re-open the issue if it is still actual
