### ISSUE TITLE
MBR description error

### ISSUE THREAD

**Issue by aleaksah** [0xAX/linux-insides#635]
> This will instruct QEMU to use the boot binary that we just built as a disk image. Since the binary generated by the assembly code above fulfills the requirements of the boot sector (the origin is set to 0x7c00 and we end with the magic sequence), QEMU will treat the binary as the master boot record (MBR) of a disk image.

"Origin is set to 0x7c00" isn't requied requirement for MBR, this is address where valid MBR will be loaded. Real requirement are:
- Be stored in first sector of drive.
- Have magic number 0x55AA.

**Comment by sakshatshinde** [comment]
Yes **0x55AA** is indeed the magic number. You need this in the last 2 **bytes** of your first 512 bytes which are read by the BIOS.  If that's what these last two bytes are, the BIOS moves the 512 bytes to the memory address **0x7c00**
