### ISSUE TITLE
The description of `initial_gs` may be wrong

### ISSUE THREAD

**Issue by hao-lee** [0xAX/linux-insides#644]
Cite from [linux-interrupts-2](https://0xax.gitbooks.io/linux-insides/content/Interrupts/linux-interrupts-2.html):

> ```
> movl    $MSR_GS_BASE,%ecx
> movl    initial_gs(%rip),%eax
> movl    initial_gs+4(%rip),%edx
> wrmsr
> ```
> Here we specified a model specific register with MSR_GS_BASE, put the 64-bit address of the `initial_gs` to the edx:eax pair and execute the wrmsr instruction for filling the gs register with the base address of the init_per_cpu__irq_stack_union which will be at the bottom of the interrupt stack.

I think the instruction `wrmsr` put the **memory content stored at `initial_gs`** to MSR, not put **the 64-bit address of the `initial_gs`** to the MSR.

**Comment by mudongliang** [comment]
@0xAX I think @hao-lee is right. %eax and %edx will store the content of `initial_gs`. The `initial_gs` is an assembling identifier which points to `irq_stack_union`.

**Comment by Mutated1994** [comment]
> Cite from [linux-interrupts-2](https://0xax.gitbooks.io/linux-insides/content/Interrupts/linux-interrupts-2.html):
> 
> > ```
> > movl    $MSR_GS_BASE,%ecx
> > movl    initial_gs(%rip),%eax
> > movl    initial_gs+4(%rip),%edx
> > wrmsr
> > ```
> > 
> > 
> > Here we specified a model specific register with MSR_GS_BASE, put the 64-bit address of the `initial_gs` to the edx:eax pair and execute the wrmsr instruction for filling the gs register with the base address of the init_per_cpu__irq_stack_union which will be at the bottom of the interrupt stack.
> 
> I think the instruction `wrmsr` put the **memory content stored at `initial_gs`** to `edx:eax`, not put **the 64-bit address of the `initial_gs`** to the edx:eax.

@hao-lee @mudongliang

Nope, dude.

For example, we would write the address of a global value stored at location labeled a as a(%rip), meaning that the assembler and linker should cooperate to compute the offset of a from the ultimate location of the current instruction.

See [Notes on x86-64 programming](http://web.cecs.pdx.edu/~apt/cs491/x86-64.pdf)

So, after assembler and linker, the `a(%rip)` just is the address of a (e.g. `0xFFFF0000`).
NOTE that is not the content of `a`.

@0xAX @initBasti

**Comment by hao-lee** [comment]
> For example, we would write the address of a global value stored at location labeled a as a(%rip), meaning that the assembler and linker should cooperate to compute the offset of a from the ultimate location of the current instruction.

Yes, `a(%rip)` can be treated as the address of label `a`. However, `mov a(%rip), rax` actually put the content at label `a` into `rax`. If you want to put the address of label `a` into `rax`, `lea a(%rip), rax` would be the correct way.

**Comment by hao-lee** [comment]
By the way, my original post has two typoes. I have fixed them.

I think the instruction `wrmsr` put the memory content stored at `initial_gs` to ~`edx:eax`~`MSR`, not put the 64-bit address of the `initial_gs` to the ~`edx:eax`~`MSR`.

**Comment by Mutated1994** [comment]
> By the way, my original post has two typoes. I have fixed them.
> 
> I think the instruction `wrmsr` put the memory content stored at `initial_gs` to ~`edx:eax`~`MSR`, not put the 64-bit address of the `initial_gs` to the ~`edx:eax`~`MSR`.

Nope, dude.

WRMSR - Write the value in EDX:EAX to MSR specified by ECX.

See [WRMSR — Write to Model Specific Register](https://www.felixcloutier.com/x86/wrmsr)

**Comment by Mutated1994** [comment]
> > For example, we would write the address of a global value stored at location labeled a as a(%rip), meaning that the assembler and linker should cooperate to compute the offset of a from the ultimate location of the current instruction.
> 
> Yes, `a(%rip)` can be treated as the address of label `a`. However, `mov a(%rip), rax` actually puts the content at label `a` into `rax`. If you want to put the address of label `a` into `rax`, `lea a(%rip), rax` would be the correct way.

mov `a(%rip)`, rax -> mov `0x1234`, rax 
The content of rax is `0x1234`.

**Comment by Mutated1994** [comment]
@hao-lee Sorry dube, you are right.

The instruction wrmsr put the memory content stored at initial_gs to MSR, and the content of initial_gs is base address of the init_per_cpu__irq_stack_union.

Demonstrated by the following code:

b.c: 
```
#include <stdio.h>

extern unsigned int initial_gs;

int main(void)
{
    printf("initial_gs = 0x%x\n", initial_gs);
    printf("&initial_gs = %p\n", &initial_gs);

    unsigned int a;
    __asm__("movl initial_gs(%rip), %eax \n\t");
    __asm__("movl %%eax, %0\n" :"=b"(a));

    printf("initial_gs = 0x%x\n", a);
    return 0;
}
```
a.s:
```
.globl initial_gs;
initial_gs:
        .quad   0x12345678; # init_per_cpu__irq_stack_union
```
Makefile:
```
TGT = main
C_SRC = $(wildcard *.c)
ASM_SRC = $(wildcard *.s)
OBJ =$(patsubst %.c,%.o,$(C_SRC))
OBJ +=$(patsubst %.s,%.o,$(ASM_SRC))
CC =gcc
$(TGT): $(OBJ)
	$(CC) -o $@ $^
clean:
	$(RM) $(TGT) *.o
```
Output: 
``` bash
root@3df2ddd23f33# ./main 
initial_gs = 0x12345678
&initial_gs = 0x5556014126b3
initial_gs = 0x12345678
```

So, I will create a pull request to resove this issue immediately.

@mudongliang @initBasti @0xAX
