### ISSUE TITLE
segment values typo

### ISSUE THREAD

**Issue by changuoqiang** [0xAX/linux-insides#647]
Booting/linux-bootstrap-1.md -> The Beginning of the Kernel Setup Stage

gs = fs = es = ds = ss = 0x10000
cs = 0x10200
 
is wrong, because in real mode, PhysicalAddress = Segment Selector * 16 + Offset

the correct is 

gs = fs = es = ds = ss = 0x1000
cs = 0x1020

just  cs = ds + 0x20

**Comment by PinoTsao** [comment]
yes, I already mentioned it in #609

**Comment by 0xAX** [comment]
should be fixed in e205c3. Thank you :+1:
