### ISSUE TITLE
What's task_works in task_struct?

### ISSUE THREAD

**Issue by mudongliang** [0xAX/linux-insides#662]
Hi @0xAX , do you know task works mechanism(maybe not a mechanism) in the linux kernel? Those task works are appended during the running of processes. Those task works will be executed after entering into user mode. There are several APIs:
- task_work_add
- task_work_cancel
- task_work_run

I have several questions about it:
1. What's its purpose(why does it exist)?
2. Why does linux kernel defer those task works to user mode?

**Comment by 0xAX** [comment]
Hello @mudongliang, no unfortunately I even didn't see such API

**Comment by mudongliang** [comment]
OK
