### ISSUE TITLE
movzbl copy a byte but not 2 bytes 

### ISSUE THREAD

**Issue by Jekton** [0xAX/linux-insides#665]
In [this post](https://github.com/0xAX/linux-insides/blob/master/Booting/linux-bootstrap-2.md) it says that `movzbl  %dl, %eax` copies the value of dl to the lower 2 bytes of the eax register, a `movzbl` is actually copies one byte（that's the letter *b* stands）

**Comment by mudongliang** [comment]
Right. Copy one byte and nullify the upper three bytes. Could you please send one PR to fix it?

**Comment by Jekton** [comment]
> Right. Copy one byte and nullify the upper three bytes. Could you please send one PR to fix it?

PR posted. #666
