### ISSUE TITLE
issues in linux-initialization-3.md

### ISSUE THREAD

**Issue by PinoTsao** [0xAX/linux-insides#676]
>So we're getting virtual address of the boot_params structure and pass it to the copy_bootdata function, where we copy real_mod_data to the boot_params which is declared in the arch/x86/include/asm/setup.h

Improvement, fix typo and error(as for the current code, maybe it is not a error before):

>So we're getting virtual address of variable `boot_params` which come along from real mode, and pass it to the copy_bootdata function, where we copy real_mode_data to the boot_params which is defined in the arch/x86/kernel/setup.c

And, of course

        extern struct boot_params boot_params;

should be changed to:

        struct boot_params boot_params;

**Comment by 0xAX** [comment]
thank you @PinoTsao, adjusted
