### ISSUE TITLE
Is there any way to forge CPU usage

### ISSUE THREAD

**Issue by caojioayue** [0xAX/linux-insides#678]
Is there any way to forge CPU usage?I don't want people to see the real CPU load by command

**Comment by yaccz** [comment]
Most tools will read the cpu usage from /proc/ so you could patch libc to intercept opens on the relavant files but 1. one could write a program for reading the cpu usage without libc using syscalls directly. 2. are there other ways to read the cpu usage? 3. Why would you do this? 4. One could use LD_PRELOAD to avoid patching libc but I suspect there is no way to force LD_PRELOAD for all processes that can't be trivially disabled.

**Comment by caojioayue** [comment]
> 大多数工具都会读取/ proc /中的cpu用法，所以你可以修补libc来拦截相关文件上的打开但是1.可以编写一个程序来直接使用系统调用来读取没有libc的cpu用法。2.还有其他方法来读取CPU使用情况吗？你为什么要这样做？4.可以使用LD_PRELOAD来避免修补libc，但我怀疑没有办法强制LD_PRELOAD用于所有不能轻易禁用的进程。

Hello, do you have any ready-made tools? Or is there an example?
