### ISSUE TITLE
Images in web version are unavailable

### ISSUE THREAD

**Issue by 0x3c3e** [0xAX/linux-insides#689]
Due https://tinypic.com/ shutdown images are no longer available.

**Comment by sjp38** [comment]
I am also suffering from this problem.  Is there any way to get those images?

**Comment by 0x3c3e** [comment]
@sjp38 I guess it's possible to extract images from pdf version somehow and re-upload to different provider

**Comment by darkstar** [comment]
I just submitted a PR that fixes all but one image from cached copies at web.archive.org

**Comment by 0x3c3e** [comment]
@darkstar as I see yours PR was merged, so I will close the issue
