### ISSUE TITLE
issue in  the content of Theory/linux-theory-1.html -- Paging

### ISSUE THREAD

**Issue by m4p1e** [0xAX/linux-insides#695]
>Userspace occupies the lower part of the virtual address space, from 0x000000000000000 to 0x00007fffffffffff and kernel space occupies the highest part from 0xffff8000000000 to 0xffffffffffffffff. Note that bits 63:48 is 0 for userspace and 1 for kernel space. 

its x86_64 
0x00007fffffffffff   =  46:0    total 47bits

*so  bits 63:47  is 0 for userspace and 1 for kernel space.*

its right? or i am wrong?

**Comment by 0xAX** [comment]
@m4p1e thank you fixed
