### ISSUE TITLE
Debuging boot setup?

### ISSUE THREAD

**Issue by thknx** [0xAX/linux-insides#697]
(I am not sure is this right place to ask, if isn't please excuse me)

Why we can see **start_kernel** symbol on GDB but not arch/boot/x86/main.c:main ? I mean I want to debug kernel's early boot setup but when I try to insert any hardware breakpoint to boot codes, gdb cannot see symbols except from kernel codes.

```
$	qemu-system-x86_64 \
		-kernel $LINUX_SOURCE/arch/x86_64/boot/bzImage \
		-append "console=ttyS0 nokaslr earlycon earlyprintk" \
		-initrd $LINUX_SYSROOT/ramdisk.img \
		-m 1024 \
		--enable-kvm \
		-cpu host \
		-s -S &

$ gdb vmlinux
> target remote :1234
> hbreak start_main
```

**Comment by tengwu** [comment]
I have the same question now.

**Comment by ZirongH** [comment]
At 2022-07-09 21:15:06, "tengwu" ***@***.***> wrote:

I have the same question now.
