### ISSUE TITLE
EIP register to IP register

### ISSUE THREAD

**Issue by h4child** [0xAX/linux-insides#699]
in `Booting/bootstrap-1.md` 
text:
`The starting address is formed by adding the base address to the value in the EIP register:`
It is IP register not EIP register in  real mode

**Comment by mudongliang** [comment]
You're right. Could you send a PR to fix this issue?

**Comment by mudongliang** [comment]
https://stackoverflow.com/questions/6917503/is-it-possible-to-use-32-bits-registers-instructions-in-real-mode
