### ISSUE TITLE
0x10ffef - linux-bootstrap-1.md

### ISSUE THREAD

**Issue by rodggerbr** [0xAX/linux-insides#700]
Booting/linux-bootstrap-1.md
text:
>where `0x10ffef` is equal to `1MB + 64KB - 16b` . . . Since `2^20 = 1048576` is 1MB.

`0x10ffef` = 1114095
`1MB + 64KB - 16b` = 1114096 (`(2^20) + (64 × 2^10) − 16`) or 2^20

`0x10ffef` != `1MB + 64KB - 16b`

maximum address = 0x10ffef
2^20 = address 0 - 0x10ffef

right:
>where `0x10ffef` is equal to `(1MB + 64KB - 16b) - 1` . . . Since `2^20 - 1 = 1048575` is 1MB.

**Comment by rodggerbr** [comment]
change to 16B
16B = bytes
16b = confuse with bits

**Comment by 0xAX** [comment]
should be fixed in 09642cab4e16e5f23283f3201f7d6220be7fc907. @rodggerbr thank you for noting :+1:
