### ISSUE TITLE
Broken Link in Cgroups

### ISSUE THREAD

**Issue by pf0** [0xAX/linux-insides#730]
Unfortunately, there appears to be a broken link in the 'Early initialization of control groups' section of 'Cgroups/linux-cgroups-1.md'. At ''This function is defined in the kernel/cgroup.c ..' there is a broken hyperlink.

The link should be changed to https://github.com/torvalds/linux/blob/16f73eb02d7e1765ccab3d2018e0bd98eb93d973/kernel/cgroup/cgroup.c or https://github.com/torvalds/linux/blob/master/kernel/cgroup/cgroup.c .

**Comment by initBasti** [comment]
Hi, I have a open pull request, that fixes that issue just needs to be merged. Thanks for the notice though.

**Comment by luohuang** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，您的邮件我已经收到。
 
谢谢！
