### ISSUE TITLE
eBook version

### ISSUE THREAD

**Issue by JamesSWilliams** [0xAX/linux-insides#740]
Hey,

really like your book, are there any plans to also release a pdf or epub?
The link show in #156 doesn't work anymore.

**Comment by initBasti** [comment]
Hey James,

we currently have a generated gitbook instance (https://0xax.gitbook.io/linux-insides/), where pdf export is sadly only available for viewers after upgrading the subscription (https://docs.gitbook.com/features/pdf-export). So currently the only option to make that pdf public would be for @0xAX to maintain an export in github, but that seems cumbersome. 

Greetings

**Comment by oryband** [comment]
@JamesSWilliams Maybe this could solve this issue? https://github.com/GitbookIO/gitbook/blob/master/docs/ebook.md

**Comment by 0xAX** [comment]
yes, for now you can only generate book in needed format, check please the link from @oryband

**Comment by siddhpant** [comment]
Please check out #837 and let me know if anything can be improved.
