### ISSUE TITLE
typo in linux-bootstrap-1.html

### ISSUE THREAD

**Issue by noway75** [0xAX/linux-insides#763]
https://0xax.gitbooks.io/linux-insides/content/Booting/linux-bootstrap-1.html

```Jump to main

That's all! We have the stack and BSS, so we can jump to the main() C function:

    calll main
```

calll main should be call ?

**Comment by priyanshumaitra** [comment]
Is anyone working on this issue?

**Comment by 0xAX** [comment]
it is not typo but correct instruction, so I am closing this issue
