### ISSUE TITLE
Hello, I am sorting out the information related to the Linux kernel. Is there anything in the repo of the big guy that I can reprint?

### ISSUE THREAD

**Issue by wenchao1024** [0xAX/linux-insides#782]
I am a developer from China and want to provide more help to Chinese Linux developers.Address of my Repo:
https://github.com/0voice/linux_kernel_wiki

**Comment by 0xAX** [comment]
hello @wenchao1024, @mudongliang did Chinese translation - https://github.com/MintCN/linux-insides-zh, so I suppose you could contact him
