### ISSUE TITLE
Starting address after reset

### ISSUE THREAD

**Issue by pim-pesochek** [0xAX/linux-insides#790]
In the beginning of the book there is statement: '_The processor starts working in real mode... it could work with 1 megabyte address space_' and later: '_The starting address is formed by adding the base address to the value in the EIP register... We get 0xfffffff0, which is 16 bytes below 4GB_'
So how the processor which can only work with 1 mb of address space can access 16 bytes below 4GB ?

**Comment by kromych** [comment]
9.1.4 First Instruction Executed
The first instruction that is fetched and executed following a hardware reset is located at physical address FFFFFFF0H. This address is 16 bytes below the processor’s uppermost physical address. The EPROM containing the software-initialization code must be located at this address.
The address FFFFFFF0H is beyond the 1-MByte addressable range of the processor while in real-address mode. The processor is initialized to this starting address as follows. The CS register has two parts: the visible segment selector part and the hidden base address part. In real-address mode, the base address is normally formed by shifting the 16-bit segment selector value 4 bits to the left to produce a 20-bit base address. However, during a hardware reset, the segment selector in the CS register is loaded with F000H and the base address is loaded with FFFF0000H. The starting address is thus formed by adding the base address to the value in the EIP register (that is, FFFF0000 + FFF0H = FFFFFFF0H).
The first time the CS register is loaded with a new value after a hardware reset, the processor will follow the normal rule for address translation in real-address mode (that is, [CS base address = CS segment selector * 16]). To insure that the base address in the CS register remains unchanged until the EPROM based software-initialization code is completed, the code must not contain a far jump or far call or allow an interrupt to occur (which would cause the CS selector value to be changed).
