### ISSUE TITLE
Publish it as a GitBook

### ISSUE THREAD

**Issue by SamyPesse** [0xAX/linux-insides#8]
It would be great to publish it as a GitBook, here is the format: https://github.com/GitbookIO/gitbook and the online platform (build CI, ...): https://www.gitbook.com

GitBook.com integrates very well with GitHub and generates nice website, for example here is my book: https://github.com/SamyPesse/How-to-Make-a-Computer-Operating-System and http://samypesse.gitbooks.io/how-to-create-an-operating-system/content/

Let me know if you're interested :beers:

**Comment by 0xAX** [comment]
Hello @SamyPesse,

yes, it is in my plans. Will publish it when will have a time and second post.

btw thank you for How-to-Make-a-Computer-Operating-System :+1:

**Comment by SamyPesse** [comment]
Nice :+1: 

Feel free to send me an email at samy[at]gitbook.com if you need any help

**Comment by 0xAX** [comment]
@SamyPesse thank you.

**Comment by 0xAX** [comment]
@SamyPesse finally published it, thank you.
