### ISSUE TITLE
[question]about virtual adress convert

### ISSUE THREAD

**Issue by luck71** [0xAX/linux-insides#840]
hello! i have a confusion about convert to va
why when enable long mode the current instruction address(rip register) still look like a physical address in gdb,
![image](https://github.com/0xAX/linux-insides/assets/86523229/4b01121b-b2b2-4aa6-bb55-f5376ab02bb9)

and untill these instructions be excuted, then all address show in gdb is virtual address
![image](https://github.com/0xAX/linux-insides/assets/86523229/5f572713-a09c-4dac-8773-15b8d2e319c5)

another question:
![image](https://github.com/0xAX/linux-insides/assets/86523229/470595b1-82cf-44ed-9f88-8271c008921f)
in long-mode(.code64), `call    __startup_64` still use pa `0x1000014       call   0x10001d0`, while $1f is va `movq    $1f, %rax`

at this moment, PG is already enabled, why call instruction still use pa `0x10001d0 (__startup_64)`

or i make a mistake, 0x10001d0 is already a va, if so, how can i find corresponding pa by boot page table manually

**Comment by luohuang** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，您的邮件我已经收到。
 
谢谢！

**Comment by luck71** [comment]
1. this call is near call, address show in gdb is plused with $pc + instruction length
2. 0x10001d0 is a va, same as pa at this moment
3. `movq    $1f, %rax` $1f is signed 32bit number, convert to signed 64 with fff padding
