### ISSUE TITLE
Impact of cgroups constraints on memory

### ISSUE THREAD

**Issue by androm3da** [0xAX/linux-insides#88]
Regarding "Linux kernel memory management" -- I'd love to hear more about what impact there is to enabling cgroups-constraints on memory.  

Empirically, I've seen that memory allocations made from within a cgroup-memory-constrained process appear to steal cycles to evict cache pages in the foreground (in order to make room for my allocation).  This has a devastating impact on worst case latency for memory allocations.

**Comment by 0xAX** [comment]
Hello @androm3da,

Unfortunatelly, I almost don't know anything about cgroups and its implementation, so i'm nut sure that i can give answer

**Comment by androm3da** [comment]
Alrighty, thanks.
